---
title: "Milestone 4: Using Tools in R"
author: "Alexandra Norris"
date: "2/28/2020"
output: bookdown::pdf_document2
# output: html_document
bibliography: bibliography.bib
link_citations: true
---

This PDF is a demonstration of my RMD PDF skills. To look at my work more fully check out my Github Repository.^[[Github repository](https://github.com/asnorris/milestone-4)]. 

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
knitr::write_bib(c("fivethirtyeight", "gtsummary"), "bibliography.bib", width = 60)

library(tinytex)
library(bookdown)
library(tidyverse)
library(gt)
library(kableExtra)
library(fivethirtyeight)
library(gtsummary)
library(bibtex)
library(tinytex)

```

### Example of me using a regression table:
```{r gt table}

# create fake data

x <- tribble(
  ~"Person", ~"Try 1", ~"Try 2", ~"Try 3",
  "A",   1,     3,     2,   
  "B",   2,    4,      5
)

# create table

x %>%
  gt() %>%
  tab_header("Number of Baskets Made", subtitle = "Out of Five Shots")

```

### Here is an example of me using a regression table using the gtsummary package:

```{r, include = FALSE}

# regression table, using college grad data

y <- fivethirtyeight::college_recent_grads %>%
filter(major_category == "Engineering" | major_category == "Arts") %>%
select(major_category, employed_fulltime)

fit <- lm(employed_fulltime ~ major_category, y)
print(fit)
```

```{r}

tbl_regression(fit)

```
 